/* eslint-disable */
// Auto-generated by npm run optimize-images - do not edit manually.

export type ImageMeta = {
  width: number;
  height: number;
  blurDataURL: string;
};

export const imageMeta: Record<string, ImageMeta> = {
  "/images/portfolio/beit-neve-yam/02.webp": { width: 1180, height: 768, blurDataURL: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAgCdASoQAAoAA4BaJQBOgB0/SvuQUoOFIAD+S99gFxDWkEVaYt9+ZJOH+Thuatt7prrJJXi/IG06r0y78zVsDb7by1YjkyXRStIdlwzAAA==" },
  "/images/portfolio/duplex-ramat-aviv/cover.webp": { width: 1024, height: 847, blurDataURL: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoQAA0AA4BaJZACdACg431QAAD9UA8F780yjmLALKN961ATT1NGUOD/5ZyIu0NI43FNxerT7vPqKltFYOx9q3rRZFHjdgYAAAA=" },
  "/images/portfolio/final-project/06-pool.webp": { width: 1600, height: 888, blurDataURL: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAQCdASoQAAkAA4BaJZQC7ACWeOQAAP7h6ve0qpsE8tPDs7o9RUM+QvUF8oxFOAb9JgBBvpxB8DlV7dG12SMdyUjxmhZSdngAAA==" },
  "/images/portfolio/joseph-bar/02.webp": { width: 1600, height: 1067, blurDataURL: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoQAAsAA4BaJYwCdAEOcbGDEAD+9uLzgfnemucJ8C9+AJQdspOLIpHm6yOOpqmo49pb9UuocSIfCCvo2h4HARu0geORGZq64trK7TufGFHeFU8dgAA=" },
};

export function getImageMeta(src: string): ImageMeta | undefined {
  return imageMeta[src];
}
